// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tiny-tiktok/service/video/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: FeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)
}
