// Code generated by goctl. DO NOT EDIT.
package types

type UserAccount struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type Status struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg "`
}

type UserToken struct {
	UserID int64  `json:"user_id "`
	Token  string `json:"token"`
}

type UserInfoWithToken struct {
	UserID int64  `form:"user_id "`
	Token  string `form:"token"`
}

type User struct {
	UserID          int64  `json:"id"`
	Username        string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int    `json:"work_count"`
	FavoriteCount   int    `json:"favorite_count"`
}

type RegisterReq struct {
	UserAccount
}

type RegisterResp struct {
	Status
	UserToken
}

type LoginReq struct {
	UserAccount
}

type LoginResp struct {
	Status
	UserToken
}

type UserInfoReq struct {
	UserInfoWithToken
}

type UserInfoResp struct {
	Status
	User *User `json:"user,omitempty"`
}
