// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: mqueue.proto

//消息队列

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KqRelationActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn     string `protobuf:"bytes,1,opt,name=Sn,proto3" json:"Sn,omitempty"`
	Status int64  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *KqRelationActionReq) Reset() {
	*x = KqRelationActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqRelationActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqRelationActionReq) ProtoMessage() {}

func (x *KqRelationActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqRelationActionReq.ProtoReflect.Descriptor instead.
func (*KqRelationActionReq) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{0}
}

func (x *KqRelationActionReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *KqRelationActionReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type KqRelationActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KqRelationActionResp) Reset() {
	*x = KqRelationActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqRelationActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqRelationActionResp) ProtoMessage() {}

func (x *KqRelationActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqRelationActionResp.ProtoReflect.Descriptor instead.
func (*KqRelationActionResp) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{1}
}

var File_mqueue_proto protoreflect.FileDescriptor

var file_mqueue_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x3d, 0x0a, 0x13, 0x4b, 0x71, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x53, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x16, 0x0a, 0x14, 0x4b, 0x71, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x32, 0x4f, 0x0a, 0x06, 0x6d, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x4b, 0x71, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x71, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x71, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqueue_proto_rawDescOnce sync.Once
	file_mqueue_proto_rawDescData = file_mqueue_proto_rawDesc
)

func file_mqueue_proto_rawDescGZIP() []byte {
	file_mqueue_proto_rawDescOnce.Do(func() {
		file_mqueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqueue_proto_rawDescData)
	})
	return file_mqueue_proto_rawDescData
}

var file_mqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqueue_proto_goTypes = []interface{}{
	(*KqRelationActionReq)(nil),  // 0: pb.KqRelationActionReq
	(*KqRelationActionResp)(nil), // 1: pb.KqRelationActionResp
}
var file_mqueue_proto_depIdxs = []int32{
	0, // 0: pb.mqueue.KqRelationAction:input_type -> pb.KqRelationActionReq
	1, // 1: pb.mqueue.KqRelationAction:output_type -> pb.KqRelationActionResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mqueue_proto_init() }
func file_mqueue_proto_init() {
	if File_mqueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqRelationActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqRelationActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqueue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqueue_proto_goTypes,
		DependencyIndexes: file_mqueue_proto_depIdxs,
		MessageInfos:      file_mqueue_proto_msgTypes,
	}.Build()
	File_mqueue_proto = out.File
	file_mqueue_proto_rawDesc = nil
	file_mqueue_proto_goTypes = nil
	file_mqueue_proto_depIdxs = nil
}
