// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: mqueue.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MqueueClient is the client API for Mqueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqueueClient interface {
	KqRelationAction(ctx context.Context, in *KqRelationActionReq, opts ...grpc.CallOption) (*KqRelationActionResp, error)
}

type mqueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMqueueClient(cc grpc.ClientConnInterface) MqueueClient {
	return &mqueueClient{cc}
}

func (c *mqueueClient) KqRelationAction(ctx context.Context, in *KqRelationActionReq, opts ...grpc.CallOption) (*KqRelationActionResp, error) {
	out := new(KqRelationActionResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/KqRelationAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqueueServer is the server API for Mqueue service.
// All implementations must embed UnimplementedMqueueServer
// for forward compatibility
type MqueueServer interface {
	KqRelationAction(context.Context, *KqRelationActionReq) (*KqRelationActionResp, error)
	mustEmbedUnimplementedMqueueServer()
}

// UnimplementedMqueueServer must be embedded to have forward compatible implementations.
type UnimplementedMqueueServer struct {
}

func (UnimplementedMqueueServer) KqRelationAction(context.Context, *KqRelationActionReq) (*KqRelationActionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KqRelationAction not implemented")
}
func (UnimplementedMqueueServer) mustEmbedUnimplementedMqueueServer() {}

// UnsafeMqueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqueueServer will
// result in compilation errors.
type UnsafeMqueueServer interface {
	mustEmbedUnimplementedMqueueServer()
}

func RegisterMqueueServer(s grpc.ServiceRegistrar, srv MqueueServer) {
	s.RegisterService(&Mqueue_ServiceDesc, srv)
}

func _Mqueue_KqRelationAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KqRelationActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).KqRelationAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/KqRelationAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).KqRelationAction(ctx, req.(*KqRelationActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Mqueue_ServiceDesc is the grpc.ServiceDesc for Mqueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mqueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.mqueue",
	HandlerType: (*MqueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KqRelationAction",
			Handler:    _Mqueue_KqRelationAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mqueue.proto",
}
