// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"tiny-tiktok/service/user/rpc/internal/logic"
	"tiny-tiktok/service/user/rpc/internal/svc"
	"tiny-tiktok/service/user/rpc/types/user"
)

type UserInfoServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserInfoServiceServer
}

func NewUserInfoServiceServer(svcCtx *svc.ServiceContext) *UserInfoServiceServer {
	return &UserInfoServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------user-----------------------
func (s *UserInfoServiceServer) Info(ctx context.Context, in *user.UserInfoReq) (*user.UserInfoResp, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}

func (s *UserInfoServiceServer) AddActivity(ctx context.Context, in *user.UpdateActivityReq) (*user.UpdateActivityResp, error) {
	l := logic.NewAddActivityLogic(ctx, s.svcCtx)
	return l.AddActivity(in)
}

func (s *UserInfoServiceServer) GetActivity(ctx context.Context, in *user.GetActivityReq) (*user.GetActivityResp, error) {
	l := logic.NewGetActivityLogic(ctx, s.svcCtx)
	return l.GetActivity(in)
}
