// Code generated by goctl. DO NOT EDIT.
// Source: mqueue.proto

package mqueue

import (
	"context"

	"tiny-tiktok/service/mqueue/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	KqRelationActionReq  = pb.KqRelationActionReq
	KqRelationActionResp = pb.KqRelationActionResp

	Mqueue interface {
		KqRelationAction(ctx context.Context, in *KqRelationActionReq, opts ...grpc.CallOption) (*KqRelationActionResp, error)
	}

	defaultMqueue struct {
		cli zrpc.Client
	}
)

func NewMqueue(cli zrpc.Client) Mqueue {
	return &defaultMqueue{
		cli: cli,
	}
}

func (m *defaultMqueue) KqRelationAction(ctx context.Context, in *KqRelationActionReq, opts ...grpc.CallOption) (*KqRelationActionResp, error) {
	client := pb.NewMqueueClient(m.cli.Conn())
	return client.KqRelationAction(ctx, in, opts...)
}
