// Code generated by goctl. DO NOT EDIT.
package types

type Status struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg "`
}

type User struct {
	UserID        int64  `json:"id"`
	Username      string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Video struct {
	Id            int64  `json:"id"`
	User          User   `json:"author"`
	PlayURL       string `json:"play_url"`
	CoverURL      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type FeedReq struct {
	Token    string `form:"token,optional"`
	LastTime int64  `form:"last_time,optional"`
}

type FeedResp struct {
	Status
	NextTime int64    `json:"next_time,omitempty"`
	Video    []*Video `json:"video_list,omitempty"`
}
