// Code generated by goctl. DO NOT EDIT.
package types

type Status struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg "`
}

type User struct {
	UserID           int64  `json:"id"`
	Username         string `json:"name"`
	FollowCount      int64  `json:"follow_count"`
	FollowerCount    int64  `json:"follower_count"`
	IsFollow         bool   `json:"is_follow"`
	Avatar           string `json:"avatar"`
	Background_image string `json:"background_image"`
	Signature        string `json:"signature"`
	Total_favorited  int64  `json:"total_favorited"`
	Work_count       int64  `json:"work_count"`
	Favorite_count   int64  `json:"favorite_count"`
}

type ActionReq struct {
	Token       string `form:"token"`
	To_user_id  string `form:"to_user_id"`
	Action_type string `form:"action_type"`
}

type ActionResp struct {
	Status
}

type FollowListReq struct {
	Token   string `form:"token"`
	User_id string `form:"user_id"`
}

type FollowListResp struct {
	Status
	FollowList []User `json:"user_list,proto3"`
}

type FollowerListReq struct {
	Token   string `form:"token"`
	User_id string `form:"user_id"`
}

type FollowerListResp struct {
	Status
	FollowerList []User `json:"user_list,proto3"`
}

type FriendListReq struct {
	Token   string `form:"token"`
	User_id string `form:"user_id"`
}

type FriendListResp struct {
	Status
	FriendList []User `json:"user_list,proto3"`
}
