// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"tiny-tiktok/service/relation/rpc/internal/logic"
	"tiny-tiktok/service/relation/rpc/internal/svc"
	"tiny-tiktok/service/relation/rpc/pb"
)

type RelationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRelationServiceServer
}

func NewRelationServiceServer(svcCtx *svc.ServiceContext) *RelationServiceServer {
	return &RelationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServiceServer) Action(ctx context.Context, in *pb.ActionReq) (*pb.ActionResp, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *RelationServiceServer) FollowList(ctx context.Context, in *pb.FollowListReq) (*pb.FollowListResp, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *RelationServiceServer) FollowerList(ctx context.Context, in *pb.FollowerListReq) (*pb.FollowerListResp, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}

func (s *RelationServiceServer) FriendList(ctx context.Context, in *pb.FriendListReq) (*pb.FriendListResp, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}
