// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package relationservice

import (
	"context"

	"tiny-tiktok/service/relation/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionReq        = pb.ActionReq
	ActionResp       = pb.ActionResp
	FollowListReq    = pb.FollowListReq
	FollowListResp   = pb.FollowListResp
	FollowerListReq  = pb.FollowerListReq
	FollowerListResp = pb.FollowerListResp
	FriendListReq    = pb.FriendListReq
	FriendListResp   = pb.FriendListResp
	User             = pb.User

	RelationService interface {
		Action(ctx context.Context, in *ActionReq, opts ...grpc.CallOption) (*ActionResp, error)
		FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*FollowListResp, error)
		FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
	}

	defaultRelationService struct {
		cli zrpc.Client
	}
)

func NewRelationService(cli zrpc.Client) RelationService {
	return &defaultRelationService{
		cli: cli,
	}
}

func (m *defaultRelationService) Action(ctx context.Context, in *ActionReq, opts ...grpc.CallOption) (*ActionResp, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}

func (m *defaultRelationService) FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*FollowListResp, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.FollowList(ctx, in, opts...)
}

func (m *defaultRelationService) FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.FollowerList(ctx, in, opts...)
}

func (m *defaultRelationService) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}
