// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	relation "tiny-tiktok/service/relation/internal/handler/relation"
	"tiny-tiktok/service/relation/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: relation.ActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: relation.FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: relation.FollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: relation.FriendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/relation"),
	)
}
